# Generated by Django 5.0.2 on 2024-02-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_subject', models.CharField(max_length=10)),
                ('teacher_address', models.CharField(max_length=10)),
            ],
        ),
    ]
